### ISSUE TITLE
Solution Branch needs updating

### ISSUE THREAD

**Issue by sachinm78** [learn-co-curriculum/html-forms#2]
The lab still fails after copying and pasting the current solution provided.  Having a working solution to check would really help students understand what proper formatting should look like.

**Comment by drakeltheryuujin** [comment]
Hi there,

Since this lesson is not a lab (there isn't a solution branch or specs), I'm having difficulty spotting the issue, so I'm going to close it for now.

If you this was meant for another lesson, raise the issue there and I'd be happy to take a second look!

As always, thanks for contributing! 💙
